{
    "nomDossier" : "${nomDossier}",
    "nom" : "${nom}",
    "prenom" : "${prenom}",
    "adresse" : "${adresse}",
    "cin" : "${cin}",  
    "montantDeCreance" : "${montantDeCreance}",
    "montantDeLHypotheque" : "${montantDeLHypotheque}",
    "montantDeLaCreance" : "${montantDeLaCreance}",
    "montantDeVersement" : "${montantDeVersement}",
    "montantsDesFrais" : "${montantsDesFrais}",
    "etat" : "${etat}",
    "statusAmiable" : "${statusAmiable}",
    "statusContentieuse" : "${statusContentieuse}",
    "statusPrecontentieuse" : "${statusPrecontentieuse}",
    "date": "${date}",
    "dateDEffetDesIr": "${dateDEffetDesIr}",
    "dateDeVersement": "${dateDeVersement}",
    "dateFinDeLHypotheque": "${dateFinDeLHypotheque}",
    "phase": "${phase}",
    "created": "${created}",
    "creator": "${creator}",
    "modified": "${modified}",
    "modifier": "${modifier}",
    "payee": "${payee}",
    "Rang": "${Rang}",
    "Valeure": "${Valeure}",
    "affectation": "${affectation}",
    "agent": "${agent}",
    "avocatAvocat": "${avocatAvocat}",
    "avocatExpert": "${avocatExpert}",
    "avocatHuissier": "${avocatHuissier}",
    "code": "${code}",
    "codepostale": "${codepostale}",
    "creances": "${creances}",
    "fraidDeDossie": "${fraidDeDossie}",
    "garant": "${garant}",
    "gouvernorat": "${gouvernorat}",
    "identifiant": "${identifiant}",
    "immatriculation": "${immatriculation}",
    "interetDeRetard": "${interetDeRetard}",
    "modeDeReglement": "${modeDeReglement}",
    "nature": "${nature}",
    "natureDeLHypothequeEnquetes": "${natureDeLHypothequeEnquetes}",
    "natureDeLaCreance": "${natureDeLaCreance}",
    "natureDuFrais": "${natureDuFrais}",
    "nomDeSaisine": "${nomDeSaisine}",
    "nomDeTiers": "${nomDeTiers}",
    "pays": "${pays}",
    "raisonSociale": "${raisonSociale}",
    "region": "${region}",
    "regionAvocat": "${regionAvocat}",
    "regionExpert": "${regionExpert}",
    "regionHuissier": "${regionHuissier}",
    "telephone": "${telephone}",
    "tiers": "${tiers}",
    "type": "${type}",
    "typeDeTiers": "${typeDeTiers}",
    "typeDuFrais": "${typeDuFrais}",
    "ville": "${ville}",
    "statut": "${statut}"
}

