auth.runAsSystem();
//Données Entreé Type JSON 
var nomDossier = json.get("nomDossier")+"";
var nom = json.get("nom")+"";
var prenom = json.get("prenom")+"";
var adresse = json.get("adresse")+"";
var cin = json.get("cin")+"";
var montantDeCreance = json.get("montantDeCreance")+"";
var montantDeLHypotheque = json.get("montantDeLHypotheque")+"";
var montantDeLaCreance = json.get("montantDeLaCreance")+"";
var montantDeVersement = json.get("montantDeVersement")+"";
var montantsDesFrais = json.get("montantsDesFrais")+"";
var etat = json.get("etat")+"";
var statusAmiable = json.get("statusAmiable")+"";
var statusContentieuse = json.get("statusContentieuse")+"";
var statusPrecontentieuse = json.get("statusPrecontentieuse")+"";
var date = json.get("date")+"";
var dateDEffetDesIr = json.get("dateDEffetDesIr")+"";
var dateDeVersement = json.get("dateDeVersement")+"";
var dateFinDeLHypotheque = json.get("dateFinDeLHypotheque")+"";
var phase = json.get("phase")+"";
var created = json.get("created")+"";
var creator = json.get("creator")+"";
var modified = json.get("modified")+"";
var modifier = json.get("modifier")+"";
var payee = json.get("payee")+"";
var Rang = json.get("Rang")+"";
var Valeure = json.get("Valeure")+"";
var affectation = json.get("affectation")+"";
var agent = json.get("agent")+"";
var avocatAvocat = json.get("avocatAvocat")+"";
var avocatExpert = json.get("avocatExpert")+"";
var avocatHuissier = json.get("avocatHuissier")+"";
var code = json.get("code")+"";
var codepostale = json.get("codepostale")+"";
var creances = json.get("creances")+"";
var fraidDeDossie = json.get("fraidDeDossie")+"";
var garant = json.get("garant")+"";
var gouvernorat = json.get("gouvernorat")+"";
var identifiant = json.get("identifiant")+"";
var immatriculation = json.get("immatriculation")+"";
var interetDeRetard = json.get("interetDeRetard")+"";
var modeDeReglement = json.get("modeDeReglement")+"";
var nature = json.get("nature")+"";
var natureDeLHypothequeEnquetes = json.get("natureDeLHypothequeEnquetes")+"";
var natureDeLaCreance = json.get("natureDeLaCreance")+"";
var natureDuFrais = json.get("natureDuFrais")+"";
var nomDeSaisine = json.get("nomDeSaisine")+"";
var nomDeTiers = json.get("nomDeTiers")+"";
var pays = json.get("pays")+"";
var raisonSociale = json.get("raisonSociale")+"";
var region = json.get("region")+"";
var regionAvocat = json.get("regionAvocat")+"";
var regionExpert = json.get("regionExpert")+"";
var regionHuissier = json.get("regionHuissier")+"";
var telephone = json.get("telephone")+"";
var tiers = json.get("tiers")+"";
var type = json.get("type")+"";
var typeDeTiers = json.get("typeDeTiers")+"";
var typeDuFrais = json.get("typeDuFrais")+"";
var ville = json.get("ville")+"";

var nomDossier = args.nomDossier;
var results = null;
var dossiers = [];

//Recherche nomDossier avec Solar
if(nomDossier){
results = search.query(
  {
      language: "fts-alfresco",
      query:"PATH:'/app:company_home/st:sites/cm:recouvrement/cm:documentLibrary/*/*' AND cm:name:'"+nomDossier+"'" ,
      sort: [{
              column: 'cm:name',
              ascending: true
          }]
  });
} 

      results[0].properties["cm:name"]=nomDossier;
      results[0].properties["drct:nom"]=nom;
      results[0].properties["drct:prenom"]=prenom;
      results[0].properties["drct:adresse"]=adresse;
      results[0].properties["drct:cin"]=cin;
      results[0].properties["drct:telephone"]=telephone;
      results[0].properties["drct:montantDeCreance"]=montantDeCreance;
      results[0].properties["drct:montantDeLHypotheque"]=montantDeLHypotheque;
      results[0].properties["drct:montantDeLaCreance"]=montantDeLaCreance;
      results[0].properties["drct:montantDeVersement"]=montantDeVersement;
      results[0].properties["drct:montantsDesFrais"]=montantsDesFrais;
      results[0].properties["drccf:etat"]=etat;
      results[0].properties["drccf:statusAmiable"]=statusAmiable;
      results[0].properties["drccf:statusContentieuse"]=statusContentieuse;
      results[0].properties["drccf:statusPrecontentieuse"]=statusPrecontentieuse;
      results[0].properties["drct:date"]=date;
      results[0].properties["drct:dateDEffetDesIr"]=dateDEffetDesIr;
      results[0].properties["drct:dateDeVersement"]=dateDeVersement;
      results[0].properties["drct:dateFinDeLHypotheque"]=dateFinDeLHypotheque;
      results[0].properties["drct:phase"]=phase;
      results[0].properties["cm:created"]=created;
      results[0].properties["cm:creator"]=creator;
      results[0].properties["cm:modified"]=modified;
      results[0].properties["cm:modifier"]=modifier;
      results[0].properties["drccf:payee"]=payee.toString();
      results[0].properties["drct:Rang"]=Rang;
      results[0].properties["drct:Valeure"]=Valeure;
      results[0].properties["drct:affectation"]=affectation;
      results[0].properties["drccf:agent"]=agent;
      results[0].properties["drct:avocatAvocat"]=avocatAvocat;
      results[0].properties["drct:avocatExpert"]=avocatExpert;
      results[0].properties["drct:avocatHuissier"]=avocatHuissier;
      results[0].properties["drct:code"]=code;
      results[0].properties["drct:codepostale"]=codepostale;
      results[0].properties["drct:creances"]=creances;
      results[0].properties["drct:fraisDeDossie"]=fraidDeDossie;
      results[0].properties["drct:garant"]=garant;
      results[0].properties["drct:gouvernorat"]=gouvernorat;
      results[0].properties["drct:identifiant"]=identifiant;
      results[0].properties["drct:immatriculation"]=immatriculation;
      results[0].properties["drct:interetDeRetard"]=interetDeRetard;
      results[0].properties["drct:modeDeReglement"]=modeDeReglement;
      results[0].properties["drct:nature"]=nature;
      results[0].properties["drct:natureDeLHypothequeEnquetes"]=natureDeLHypothequeEnquetes;
      results[0].properties["drct:natureDeLaCreance"]=natureDeLaCreance;
      results[0].properties["drct:natureDuFrais"]=natureDuFrais;
      results[0].properties["drct:nomDeSaisine"]=nomDeSaisine;
      results[0].properties["drct:nomDeTiers"]=nomDeTiers;
      results[0].properties["drct:pays"]=pays;
      results[0].properties["drct:raisonSociale"]=raisonSociale;
      results[0].properties["drct:region"]=region;
      results[0].properties["drct:regionAvocat"]=regionAvocat;
      results[0].properties["drct:regionExpert"]=regionExpert;
      results[0].properties["drct:regionHuissier"]=regionHuissier;
      results[0].properties["drct:telephone"]=telephone;
      results[0].properties["drct:tiers"]=tiers;
      results[0].properties["drct:type"]=type;
      results[0].properties["drct:typeDeTiers"]=typeDeTiers;
      results[0].properties["drct:typeDuFrais"]=typeDuFrais;
      results[0].properties["drct:ville"]=ville;
      results[0].save();
 
    

   model.dossiers = dossiers;
   model.nomDossier = nomDossier;
   model.nom = nom;
   model.prenom = prenom;
   model.adresse = adresse;
   model.cin = cin;
   model.montantDeCreance = montantDeCreance;
   model.montantDeLHypotheque = montantDeLHypotheque;
   model.montantDeLaCreance = montantDeLaCreance;
   model.montantDeVersement = montantDeVersement;
   model.montantsDesFrais = montantsDesFrais;
   model.etat = etat;
   model.statusAmiable = statusAmiable;
   model.statusContentieuse = statusContentieuse;
   model.statusPrecontentieuse = statusPrecontentieuse;
   model.date = date;
   model.dateDEffetDesIr = dateDEffetDesIr;
   model.dateDeVersement = dateDeVersement;
   model.dateFinDeLHypotheque = dateFinDeLHypotheque;
   model.phase = phase;
   model.created = created;
   model.creator = creator;
   model.modified = modified;
   model.modifier = modifier;
   model.payee = payee;
   model.Rang = Rang;
   model.Valeure = Valeure;
   model.affectation = affectation;
   model.agent = agent;
   model.avocatAvocat = avocatAvocat;
   model.avocatExpert = avocatExpert;
   model.avocatHuissier = avocatHuissier;
   model.code = code;
   model.codepostale = codepostale;
   model.creances = creances;
   model.fraidDeDossie = fraidDeDossie;
   model.garant = garant;
   model.gouvernorat = gouvernorat;
   model.identifiant = identifiant;
   model.immatriculation = immatriculation;
   model.interetDeRetard = interetDeRetard;
   model.modeDeReglement = modeDeReglement;
   model.nature = nature;
   model.natureDeLHypothequeEnquetes = natureDeLHypothequeEnquetes;
   model.natureDeLaCreance = natureDeLaCreance;
   model.natureDuFrais = natureDuFrais;
   model.nomDeSaisine = nomDeSaisine;
   model.nomDeTiers = nomDeTiers;
   model.pays = pays;
   model.raisonSociale = raisonSociale;
   model.region = region;
   model.regionAvocat = regionAvocat;
   model.regionExpert = regionExpert;
   model.regionHuissier = regionHuissier;
   model.telephone = telephone;
   model.tiers = tiers;
   model.type = type;
   model.typeDeTiers = typeDeTiers;
   model.typeDuFrais = typeDuFrais;
   model.ville = ville;
   model.statut = "succees";